version: '3.1'

services:
  postgres:
    image: postgres:11.5
    container_name: be-infra-development-pg
    ports:
      - "5430:5432"
    restart: always
    environment:
      POSTGRES_USER: devPostgresUser
      POSTGRES_PASSWORD: devPostgresPassword
      POSTGRES_DB: be-infra
  redis: 
    image: redis:6.0
    container_name: be-infra-development-redis
    command: redis-server --requirepass devRedisPassword
    ports:
      - "6379:6379"
    restart: always